# Generated by Django 5.2 on 2025-05-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_closed_listing_final_price_listing_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
